source 'https://rubygems.org'

gem 'rails',   '4.0.4'
gem 'sqlite3', '1.3.9'

gem 'sass-rails',   '4.0.3'
gem 'uglifier',     '2.5.0'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.1.0'
gem 'turbolinks',   '2.2.2'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '1.5.3'

# Use debugger
gem 'debugger', '1.6.6', group: [:development, :test]

# Add rspec to both development and test groups for generators
gem 'rspec-rails', '2.14.2', group: [:development, :test]
group :test do
  gem 'capybara',         '2.2.1'
  gem 'database_cleaner', '1.2.0'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', '0.4.0', require: false
end

